### ISSUE TITLE
为啥我跑了一个小时还没结束？

### ISSUE THREAD

**Issue by alterem** [doveppp/linuxdo-checkin#4]
为啥我跑了一个小时还没结束？
<img width="734" alt="image" src="https://github.com/user-attachments/assets/da0feb2f-55a3-4309-bb58-f7252bd51741">

**Comment by doveppp** [comment]
程序应该没有可以导致死循环的东西也，刚才加了些日志，更新下然后重新运行试试

**Comment by alterem** [comment]
<img width="586" alt="image" src="https://github.com/user-attachments/assets/0ae743e3-6d4c-4b51-9632-0f90e7ea7e24">
现在是这样

**Comment by doveppp** [comment]
USERNAME  和 PASSWORD 设置了吗

**Comment by alterem** [comment]
<img width="1211" alt="image" src="https://github.com/user-attachments/assets/ec925910-6304-4687-bdf2-3bd7c10c04fe">
设置了a啊

**Comment by doveppp** [comment]
clone到本地试试呢

**Comment by alterem** [comment]
> clone到本地试试呢

我看你的action执行都没问题啊

**Comment by doveppp** [comment]
> > clone到本地试试呢
> 
> 我看你的action执行都没问题啊

是啊，我本地、action都没问题，不知道你的咋回事

**Comment by alterem** [comment]
我尝试本地运行，第一次出错，第二次失败，然后actions还是失败，后面我改成 Chromium 成功了
